### ISSUE TITLE
reuse existing ovf instead of deleting

### ISSUE THREAD

**Issue by kikitux** [YungSang/fedora-atomic-packer#5]
Hello, I am running  my first make on this, and it's downloading the information over the network.

I think the 2nd time it will delete everything and doit again.. right?

in such case, perhaps an option would be:
- Keep the ovf output of the first run
- use virtualbox-ovf on the 2nd run and just do upgrade if ovf exits
- default to virtuabox-iso if ovf doesn't exist 

What do you think?

**Comment by YungSang** [comment]
@kikitux Thank you for your suggestion.

That would be great and much faster to build.
I have just a concern about the size of a box with two repos in this case.
Do you know how to remove the old ostree repo gracefully after upgrading?

**Comment by YungSang** [comment]
Or having two repos might be good for fallback.

**Comment by YungSang** [comment]
I found it.

```
# ostree admin undeploy 1
```

**Comment by kikitux** [comment]
this is an output when I did atomic upgrade, and created a new entry.. check *

ostree admin status
  fedora-atomic a09ce2f824443cbe269173b77501ba4d9f6859104f1e3a98dcd71802a76dc39a.1
    origin refspec: fedora-atomic:fedora-atomic/rawhide/x86_64/docker-host
- fedora-atomic 7cd239a8947a75989c11a252debb4dd4e4b26909152a6e00e5eb504b71ee4124.0
  origin refspec: fedora-atomic:fedora-atomic/rawhide/x86_64/docker-host

after reboot,..

[vagrant@localhost ~]$ ostree admin status
- fedora-atomic a09ce2f824443cbe269173b77501ba4d9f6859104f1e3a98dcd71802a76dc39a.1
  origin refspec: fedora-atomic:fedora-atomic/rawhide/x86_64/docker-host
  fedora-atomic 7cd239a8947a75989c11a252debb4dd4e4b26909152a6e00e5eb504b71ee4124.0
    origin refspec: fedora-atomic:fedora-atomic/rawhide/x86_64/docker-host

[vagrant@localhost ~]$ sudo ostree admin undeploy 1
Transaction complete; bootconfig swap: yes deployment count change: -1
Freed objects: 97.6 MB
Deleted deployment 7cd239a8947a75989c11a252debb4dd4e4b26909152a6e00e5eb504b71ee4124.0
[vagrant@localhost ~]$

**Comment by YungSang** [comment]
I will try to make `upgrade` to build a new box from the current box.

**Comment by kikitux** [comment]
Did a sample template_upgrade.json for your review.

https://github.com/YungSang/fedora-atomic-packer/pull/6

I haven't tested as for some reason the make fails due something on sudo..

**Comment by kikitux** [comment]
updated the PR
