### ISSUE TITLE
make fail due sudoers issues

### ISSUE THREAD

**Issue by kikitux** [YungSang/fedora-atomic-packer#7]
For some reason my make run fail

any hint?

https://gist.github.com/kikitux/d37b67c6a8dd1a76656e

**Comment by YungSang** [comment]
Are you useing `Downloading or copying: file:///Volumes/hd1/Dropbox/work/packer-vagrant/fedora-atomic-packer/boot.iso` instead of OVF?
I guess that is a problem.

**Comment by kikitux** [comment]
deleted and running again..

I am running a copy of the project on github  as is.. no changes

will report back soon

z2-3:fedora-atomic-packer kikitux$ rm boot.iso

z2-3:fedora-atomic-packer kikitux$ make | tee make.log

curl -LO
http://rpm-ostree.cloud.fedoraproject.org/project-atomic/install/rawhide/20140708.0/boot.iso

  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current

```
                             Dload  Upload   Total   Spent    Left
```

Speed

 25  750M   25  193M    0     0  22.9M      0  0:00:32  0:00:08  0:00:24
26.2M

**Comment by YungSang** [comment]
Oh are you trying to build from scratch instal of upgrade?

**Comment by kikitux** [comment]
from scratch install, for some reason is not working for me.

did a new git clone, failed.

deleted the boot.iso and i am trying again..

**Comment by YungSang** [comment]
Strange... Do you see the boot command in a VirtualBox GUI window?

**Comment by kikitux** [comment]
the machine boots
install.
run the commands,, with those warnings..
reboot
i see the gui…
it fail to shutdown.

gui is left running, i can login as vagrant/vagrant but sudo fail with same warning..

perhaps once the box is created something did change on atomic repo ???

**Comment by YungSang** [comment]
> i see the gui…
> it fail to shutdown.

This is a problem.
After installation is complete, the boot config will set sudo setting.
see http/atomic-ks.cfg

**Comment by YungSang** [comment]
I experience a sudo problem as well in the latest installation. Umm...

**Comment by kikitux** [comment]
ithink something changed upstream

**Comment by YungSang** [comment]
Yup.

Anyway, I have created the upgraded box and tested it.
It is over 100 MB bigger than the original box...

**Comment by kikitux** [comment]
any faster than pulling all from internet?

**Comment by YungSang** [comment]
Yes, it's much faster. Thank you so much for your idea.

When the sudo problem is fixed, I will release it.

**Comment by kikitux** [comment]
can you push to a dev branch?

**Comment by YungSang** [comment]
https://github.com/YungSang/fedora-atomic-packer/tree/upgrade

**Comment by kikitux** [comment]
ok, seems i found the issue.. there is a hidden ^M character in http/atomic-ks.cfg

on the line cat << EOF > /etc/sudoers.d/vagrant^M

did you edit on windows? I am on OSX.

so the file gets created like that on the linux vm

I did login as root/vagrant did an ls and saw the issue.

**Comment by YungSang** [comment]
Oh really? I'm on OSX. I will check it.

**Comment by kikitux** [comment]
yeah, got pass that part immediately :+1:  :smile:

**Comment by YungSang** [comment]
I don't see any hidden character in it...

**Comment by kikitux** [comment]
i did dos2unix and rertry and work..  the base box build finally

command i run:
dos2unix http/atomic-ks.cfg 

after that..
==> Builds finished. The artifacts of successful builds are:
--> virtualbox: VM files in directory: output-virtualbox
--> virtualbox: 'virtualbox' provider box: ../fedora-atomic-virtualbox.box
z2-3:fedora-atomic-packer kikitux$

**Comment by YungSang** [comment]
Umm.. It is not a dos format on my local OSX.

**Comment by YungSang** [comment]
BTW, how long does it take to build it from scratch on your side?

**Comment by YungSang** [comment]
In my case, `systemd-hostnamed` in the latest one has something wrong.
`sudo hostnamectl set-hostname something.domain.name` fails.

**Comment by kikitux** [comment]
i am running it again. did make clean, now I am running as

time make | tee make.log

so will capture time and will check logs.. i didn't notice some commands
fail.

will check logs once it finish

**Comment by YungSang** [comment]
@kikitux Thank you so much for your help.

**Comment by kikitux** [comment]
all good.. I did really like the way you used make here to build the
system, and how you have make test.

I can see the value..

I have a lot of machines that I build, and reuse, and I  am using shell
scripts at the moment, but make is way more cooler and better.. will try to
see what I can get

**Comment by YungSang** [comment]
Because I don't have a good network here, so it is too slow to build it... over 2 hours...

**Comment by YungSang** [comment]
Thanks a lot.

My wifi connection has something wrong currently. I will check it again later.

**Comment by kikitux** [comment]
Time, this is a mac mini in usa.

real    14m26.198s

user    0m35.223s

sys     0m10.166s

Did update the gist with the outputs of make upo and make test

https://gist.github.com/kikitux/d37b67c6a8dd1a76656e

**Comment by YungSang** [comment]
That log looks good. Thanks again.
